### ISSUE TITLE
NoSuchMethodError: org.apache.http.params.HttpConnectionParams.setSoKeepalive

### ISSUE THREAD

**Issue by mehanika** [agorapulse/gradle-asset-pipeline-cdn#3]
When I run `assetCompile uploadAssets` Im getting this exception 
`java.lang.NoSuchMethodError:org.apache.http.params.HttpConnectionParams.setSoKeepalive(Lorg/apache/http/params/HttpParams;Z)V`

Here 's the full stack trace [Error log](https://gist.github.com/mehanika/f0de2cba489916dca406#file-log-txt).

**Comment by benorama** [comment]
It looks like some dependencies conflicts.
Could you check gradle dependencies?

**Comment by mehanika** [comment]
I have finally found the conflict @benorama, here's the [dependencies insights](https://gist.github.com/mehanika/8da372479be4bc7cdb5e). As you can see, at line [#1](https://gist.github.com/mehanika/8da372479be4bc7cdb5e#file-dependency-log-L1), [#8](https://gist.github.com/mehanika/8da372479be4bc7cdb5e#file-dependency-log-L8) and [#12](https://gist.github.com/mehanika/8da372479be4bc7cdb5e#file-dependency-log-L12) there's a dependency conflict caused by **com.bertramlabs.plugins:karman-core**. 

I made a PR to resolve this confilict #4

**Comment by mehanika** [comment]
Even though I found the conflict I still was having the exception `java.lang.NoSuchMethodError:org.apache.http.params.HttpConnectionParams.setSoKeepalive(Lorg/apache/http/params/HttpParams;Z)V`

But I finally solved!, those are the steps I followed
- 1. Add the following task to find the conflicts:

```
task buildscriptDependencies(type: DependencyReportTask) {
    configurations = [buildscript.configurations.classpath]
}
```
- 2.  Modified the `buildscript` part of my `gradle.build`, for looking like this:

```
buildscript {

  repositories {
    .... more repos here
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }

  dependencies {
    classpath "com.bertramlabs.plugins:asset-pipeline-gradle:2.6.9"
    classpath ("gradle.plugin.agorapulse.plugins:asset-pipeline-cdn:0.1.3")
  }

   configurations.classpath.exclude group: 'org.apache.httpcomponents'
   configurations.classpath.exclude group: 'com.amazonaws'
}
```

**Comment by benorama** [comment]
Ok, it's really strange that we don't have this issue on our Grails3 projects.
